### ISSUE TITLE
这个地方bool型好像只能用store_true这种形式，而不能像别的参数那样指定bool类型然后通过`--arg True`修改，知道是为啥么？

### ISSUE THREAD

**Issue by maqy1995** [soda-lsq/Python#1]
https://github.com/soda-lsq/Python/blob/503b67db0e8a86833f4427dd04a92d8c6216d6b8/python_argparse.py#L26-L27

**Comment by soda-lsq** [comment]
不用store_true的话应该可以通过指定变量类型加设置默认值，这样写可以运行，一样的效果。
parser.add_argument('--no-cuda-bool', type=bool, default=False,
                        help='disables CUDA training')

**Comment by maqy1995** [comment]
你可以试试，运行参数设置 --no-cuda-bool True，看这个Flase有没有变...

**Comment by maqy1995** [comment]
你试试把默认值设置为True，然后添加参数 `--no-cuda-bool False`，看看有没有变。反正我这边还是True，像是个bug，或者说是个坑。。很容易坑人。

**Comment by soda-lsq** [comment]
是这样吗？
```
parser.add_argument('--no-cuda-bool', type=bool, default=True, help='disables CUDA training')    # 添加参数默认值是False
args = parser.parse_args()     # 解析参数
args.no_cuda_bool=False      # 修改参数值为False
```

**Comment by maqy1995** [comment]
就是运行python的时候指定。比如这个py文件是argParseTest.py,你运行`python argParseTset.py --no-cuda-bool False`正常应该是修改了这个参数值。

**Comment by soda-lsq** [comment]
我刚刚试了，在命令行里修改默认值是True的bool参数为False，确实没有改过来。但是反过来可以，可以修改默认值是False的bool参数。这是个bug？所以以后要么用store_true，要么设置默认值是False？

**Comment by maqy1995** [comment]
反过来的话，你设置默认值为False，但是你添加参数再设置一次False，你看它还是打印出True的。。。。总之这个地方就是有问题，是一个大坑。bool型的还是用`store_ture`才行。
